### ISSUE TITLE
incoming and outgoing calls

### ISSUE THREAD

**Issue by ASA113** [Dil3mm4/labyrinth_kernel_prague#10]
Good day! I installed your kernel on the P20 Lite Ane-lx1, everything works fine, but I can't make and receive calls. After installation did wipe. How can I fix this problem? Thank you very much for your great work!

**Comment by penn5** [comment]
Perform a system downgrade with HurUpdater.
I can't remember the build number to roll back to but imo use June, it makes it easy to recover from bootloops

**Comment by ASA113** [comment]
Thank! I am installing to the latest version, perhaps because of this problem.
