### ISSUE TITLE
postmarketOS port

### ISSUE THREAD

**Issue by ghost** [Dil3mm4/labyrinth_kernel_prague#12]
Is there a postmarketOS port for the p8 lite?

https://wiki.postmarketos.org/wiki/Honor_9_Lite_(huawei-leland) links to this repository, does this mean this kernel could be used for a port?

**Comment by nahil1** [comment]
I don't know if a port specifically for p8 lite exists, but yes, you can use this kernel to build pmOS. Under the hood it's pretty much the same device. Differences are stuff like camera, tp and some sensors. Only small changes will be needed if any at all.

**Comment by ghost** [comment]
I found a matching kernel. And I can compile. But it won't boot.
Is there a slight chance you know what causes the panic? :sweat_smile: 
https://gitlab.com/postmarketOS/pmaports/-/merge_requests/1234
