### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Linx99** [Dil3mm4/labyrinth_kernel_prague#13]
`xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

**Comment by nahil1** [comment]
This does not help at all. Post your entire build log, including the commands you ran.

**Comment by Ozwald1** [comment]
I can confirm (tried with Hallium), any 'make'  command fails with same with r2 and r2.2. 
`xz: (stdin): Tiedostomuotoa ei tunnistettu
tar: Child returned status 1
tar: Error is not recoverable: exiting now
xz: (stdin): Tiedostomuotoa ei tunnistettu
tar: Child returned status 1
tar: Error is not recoverable: exiting now
scripts/kconfig/mconf  Kconfig
net/Kconfig:83: can't open file "net/wireguard/Kconfig"
make[1]: *** [scripts/kconfig/Makefile:28: menuconfig] Virhe 1
make: *** [Makefile:592: menuconfig] Virhe 2
`

Stable branch starts to build but fails later with: 

/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here

**Comment by Ozwald1** [comment]
Tiedostomuotoa ei tunnistettu == Unknown file format, sorry forgot LANG=C

**Comment by Ozwald1** [comment]
The prob is with Wireguard fetching script, I'll look more later, but that unregonized file is wireguard which isn't actually downloaded..
