### ISSUE TITLE
build error, pointing to WL_blocker

### ISSUE THREAD

**Issue by mrmazakblu** [Dil3mm4/labyrinth_kernel_prague#4]
I'm getting this error, during build.

/home/v-user/android/honor/labyrinth_kernel_prague/drivers/base/power/boeffla_wl_blocker.c:213:35: error: expected ‘)’ before ‘bbd_wake_lock’
sprintf(list_wl_default, "%s", LIST_WL_DEFAULT);

I see this comment added last year, so I assume it is problem with my system. But can you confirm, if it is problem in source.

**Comment by Dil3mm4** [comment]
I'm pushing changes so frequently that I dunno where to point you at, at the moment, since I dunno on which commit nor branch you're on. 

Also, fork the kernel for better tracking and help (and to avoid cloning and reuploading with authorship loss).

**Comment by mrmazakblu** [comment]
I commented out "boeffla_wl_blocker" from "driver/base/power" makefile and the kernel now builds for me.

**Comment by Dil3mm4** [comment]
https://github.com/Dil3mm4/labyrinth_kernel_prague/commit/4691544d3f00194b24b19c886b4cdd84eb3abe44
