### ISSUE TITLE
Device?

### ISSUE THREAD

**Issue by penn5** [Dil3mm4/labyrinth_kernel_prague#5]
Nice kernel... But for what device? Any hi6250? I see it has hi6250 drivers...

**Comment by nahil1** [comment]
Yes it is compatible with all hi6250 devices

**Comment by Dil3mm4** [comment]
I do not guarantee anything other than Prague devices, since that's the one I can currently say things about. 
But should be compatible on any hi6250 platform as @NeonDragon1909 said.
