### ISSUE TITLE
Has Westwood been removed

### ISSUE THREAD

**Issue by governos** [Dil3mm4/labyrinth_kernel_prague#8]
I'm running AOSPExtended 9.0 on my PRA-LX1 C432.
I've just updated the kernel to the 2.1 that neondragon posted on the [XDA thread.](https://forum.xda-developers.com/showpost.php?p=78298986&postcount=124) 

Using EX Kernel Manager, under TCP congestion algorithm, I no longer see Westwood. My options are cubic, reno and bbr. 

I would like to know if this is a change to the kernel or a problem on my end, please. Sorry to bother you, but I was unable to find a commit related to this issue. 

Thank you.

**Comment by penn5** [comment]
https://github.com/Dil3mm4/labyrinth_kernel_prague/blob/labyrinth_r2/arch/arm64/configs/labyrinth_defconfig#L701 is the same as in r2.1, so I'd say, no, it hasn't been intentionally removed.

However, it doesn't show up for me in Kernel Manager either.

**Comment by governos** [comment]
That's strange. I wonder if it's just me then.

On 6 December 2018 12:38:04 WET, penn5 <notifications@github.com> wrote:
>https://github.com/Dil3mm4/labyrinth_kernel_prague/blob/labyrinth_r2/arch/arm64/configs/labyrinth_defconfig#L701
>is the same as in r2.1, so I'd say, no, it hasn't been intentionally
>removed.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Dil3mm4/labyrinth_kernel_prague/issues/8#issuecomment-444857391

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by penn5** [comment]
Nope, it's the same for me

**Comment by governos** [comment]
Well, if it's possible, it would be nice to have it back. I was using it in RROS Oreo, it performed noticeably better than cubic. 

Thanks for the help.

**Comment by penn5** [comment]
You should open a new issue asking for it to be added back, if you want it.

**Comment by governos** [comment]
I will. I am really noticing a difference in Wi-Fi performance.

Thank you for the help.
