### ISSUE TITLE
Add Westwood back

### ISSUE THREAD

**Issue by governos** [Dil3mm4/labyrinth_kernel_prague#9]
I have flashed labyrinth v2.1 and noticed that the TCP compression algorithm Westwood isn't present anymore. This has been confirmed in [this issue.](https://github.com/Dil3mm4/labyrinth_kernel_prague/issues/8)

I would like to ask for this option back. I was using it in RROS Oreo under labyrinth 1.3, and noticed an improvement both in the timing of connection dropping and general connection stability. 

Thank you for your hard work and for making this available for all of us.

**Comment by nahil1** [comment]
Ah sorry. I seem to have messed up the defconfig at some point and its set to build as a module. Ill consider a rebuiding it soon. Or if you're willing to do it, i can tell you how.

**Comment by governos** [comment]
I am willing, please explain it to me.

Thanks for the attention.
